; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

build_unflags = -std=gnu++11
build_flags = 
    -std=c++14
    -I include/
    -I lib/
    -Wall
    -Wextra
    -D SH110X_NO_SPLASH

lib_ldf_mode = deep+

src_filter =
    +<*>
    +<../lib/StateMachine/*.cpp>
    +<../lib/EmotionEngine/*.cpp>
    +<../lib/ExpressionEngine/*.cpp>
    +<../lib/EyeRenderer/*.cpp>
    +<../lib/AnimationEngine/*.cpp>

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SH110X@^2.1.10
    adafruit/RTClib@^2.1.3
    Wire
    SPI

[env:uno_test]
extends = env:uno
build_flags =
    -std=c++14
    -I include/
    -I lib/
    -Wall
    -Wextra
    -D SH110X_NO_SPLASH
    ; Enable only one validation test at a time due to Uno R3 Flash limits:
    -D RUN_GAZE_TESTS
    ;-D RUN_BLINK_TESTS
    ;-D RUN_ANIMATION_TESTS
